name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v2.3.4
      - name: Build Docker image
        run: docker build -t figlet .
      - name: Test Docker image
        run: docker run --rm figlet Hello
